x-logging: &x-logging
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "10m"

services:
  geo:
    container_name: geo
    <<: *x-logging
    image: geo-dev
    build:
      context: .
      args:
        TESTING: true
    ports:
      - 8080:80
    volumes:
      - ./app:/usr/src/code/app
      - ./src:/usr/src/code/src
      # - ./vendor:/usr/src/code/vendor
    entrypoint:
      - php
      - -e
      - app/http.php
    environment:
      - GEO_ENV
      - GEO_SECRET
      - GEO_LOGGING_PROVIDER
      - GEO_LOGGING_CONFIG
